[paths]
dbf_directory = ../mockDBF/CANCFDI.DBF
sql_output = ../

[features]
# Mode can be: empty or raw (fields as they are), basic (add pk only), timestamp (pk + created_at), audit (pk + created_at + updated_at)
table_mode = basic
# When true, generates SQL preview files instead of executing them
preview_mode = true
#preview file extension txt or sql
preview_ext = txt
# When true, executes the query, dont do anything, just create the preview file if preview mode enabled
execute_query = false
# When true, use the value of the 'table_name' config option to name the table instead of the default name
custom_table_name_en = true
table_name = test_py_table

