[paths]
dbf_directory = ../mockDBF/CANCFDI.DBF
sql_output_directory = ../

[database]
host = localhost
port = 5432
database = a
user = b
password = c

[features]
# Mode can be: basic (pk only), timestamp (pk + created_at), audit (pk + created_at + updated_at)
table_mode = basic
# When true, generates SQL preview files instead of executing them
preview_mode = true
#preview file extension txt or sql
preview_ext = txt
# When true, executes the query, dont do anything, just create the preview file if preview mode enabled
execute_query = false